name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # First setup Java 17 for Android SDK tools
    - name: Set up JDK 17 (for Android tools)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    # Then switch to Java 11 for your app build (if needed)
    - name: Set up JDK 11 (for app build)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'

    - name: Add Android SDK to PATH
      run: |
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH

    - name: Build project
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test
